# ----------------------------------------
# Created on: Sun Nov 14 19:40:03 2021
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/debug/jtag_dm.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/ex.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/rom.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/utils/gen_buf.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/tinyriscv.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/clint.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/soc/tinyriscv_soc_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/id.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/id_ex.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/ctrl.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/spi.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/if_id.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/div.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/ram.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/utils/gen_dff.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/utils/full_handshake_rx.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/csr_reg.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/pc_reg.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/debug/jtag_driver.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/regs.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/core/rib.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/utils/full_handshake_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/gpio.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/timer.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/uart.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/debug/jtag_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/debug/uart_debug.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/perips/pwm.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/Desktop/key_filter.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/bcd_8421.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/data_conv.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/DHT22_driver.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/HEX8.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/OLED_drive.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/top_module.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/rtl/uart_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/uart/hc05_top.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/uart/uart_rx.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/uart/uart_tx.v" -work work
vlog   "C:/Users/Misaka/Desktop/my_riscv_soc_sim_11.11/source/soc_tb.v" -work work

# ----------------------------------------
