# ----------------------------------------
# Created on: Sun Nov 14 19:40:03 2021
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work soc_tb
add wave *
view wave
view structure
view signals

run 3ms

# ----------------------------------------
